Add Crypto Chemistry gentx
TheMarstonConnell/mainnet pull request #21
Opened 2022-10-24 13:37 UTC by Relyte

2022-10-24 14:36 UTC, TheMarstonConnell requested changes
Please also submit your genesis file

2022-10-24 15:03 UTC, karnthis approved these changes
lgtm

2022-10-24 15:13 UTC, TheMarstonConnell approved these changes

2022-10-25 01:18 UTC, karnthis commented
done

2022-10-25 01:18 UTC, closed without merging