Add files via upload
TheMarstonConnell/mainnet pull request #4
Opened 2022-10-22 15:49 UTC by smartnodesvalidators

2022-10-22 19:49 UTC, karnthis requested changes
Please include your genesis.json

2022-10-23 02:20 UTC, smartnodesvalidators commented
Done

2022-10-23 02:22 UTC, karnthis approved these changes

2022-10-23 02:22 UTC, karnthis commented
lgtm

2022-10-25 00:50 UTC, merged