add frens gentx and update genesis.json
TheMarstonConnell/mainnet pull request #8
Opened 2022-10-23 09:19 UTC by marcmacmac

2022-10-23 15:22 UTC, karnthis requested changes
gentx validation failed. please recreate your gentx after verifying all settings from the template are present and the chain-id is set correctly. Additionally, please do not modify the gentx in any way after creation. thanks!

2022-10-23 15:55 UTC, marcmacmac commented
uff ... sorry! i reused the testnet command. sorry for that! should be correct now.

2022-10-23 17:23 UTC, karnthis approved these changes

2022-10-25 00:59 UTC, karnthis commented
done

2022-10-25 00:59 UTC, closed without merging